apiVersion: apps/v1
kind: Deployment
metadata:
  name: restoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restoapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: restoapp
    spec:
      containers:
        - name: restoapp
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m