FROM openjdk:8-jdk-alpine

#ENV DB_URL=
#ENV DB_USERNAME=
#ENV DB_PASSWORD=

#ENV MAIL_HOST=
#ENV MAIL_PORT=
#ENV MAIL_USERNAME=
#ENV MAIL_PASSWORD=

ARG JAR_FILE=target/*.jar

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","/app.jar"]