apiVersion: v1
kind: Service
metadata:
  name: restoapp-internal-service
spec:
#  type: LoadBalancer
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: restoapp

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: restoapp-ingress-service
#  labels:
#    app: ${CI_PROJECT_NAME}
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    ingress.kubernetes.io/whitelist-source-range: "127.0.0.1"
spec:
  backend:
    serviceName: restoapp-internal-service
    servicePort: 8080
  tls:
    - secretName: resto-app-ssl-cert
#    - hosts:
#        - dev-pin-cms-api.a.com
#  rules:
#    - host: dev-pin-cms-api.a.com
#      http:
#        paths:
#          - pathType: Prefix
#            path: /api/admin
#            backend:
#              serviceName: ${CI_PROJECT_NAME}
#              servicePort: http
